% Bivariate Normal PDF
%
function P = bvnpdf(X,MU,SIGMA)

SIGX = sqrt(SIGMA(1:4:numel(SIGMA))); SIGX = SIGX(:);
SIGY = sqrt(SIGMA(4:4:numel(SIGMA))); SIGY = SIGY(:);
ro   =      SIGMA(2:4:numel(SIGMA))'./SIGX./SIGY; ro = ro(:);

if size(X,2)~=2
    if size(X,1)==2
        X = X';
    else
        error('Provide coordinates as a two column [x,y] matrix\n')
    end
end

%P = 1./(2*pi*sqrt(det(SIGMA))) .* exp(-0.5 * ...
P = 1./(2*pi*SIGX.*SIGY.*sqrt(1-ro.^2)) .* exp(-0.5 .* ...
    ...
    (1./(1-ro.^2)) .* (...
    ...
    (X(:,1) - MU(:,1)).^2 ./ SIGX.^2 + ...
    (X(:,2) - MU(:,2)).^2 ./ SIGY.^2 + ...
    -2*ro./(SIGX.*SIGY) .* (X(:,1)-MU(:,1)).*(X(:,2)-MU(:,2))...
    ...
    )...
    );

end